### ISSUE TITLE
下载视频异常

### ISSUE THREAD

**Issue by PGzxc** [keguoyu/kuaishou-spider#1]
* 视频无法下载(为空)
* 图片可以下载，与输入id无关联

**Comment by keguoyu** [comment]
应该是快手做了反爬的机制 正在处理

**Comment by keguoyu** [comment]
已经进行了处理

**Comment by PGzxc** [comment]
如下图：只能下载图片，不能下载视频
![][1]


[1]:http://q305e11ev.bkt.clouddn.com/spider-images.png
